# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 350dfe2ecd76e51f8c58aa787c814ef8d82a5255a263721d8ed52d18be431b0fadf2970c787ab1cfc91c96381d9debb6ef7e7599c2c86d7897ffa344a6584932

test:
  secret_key_base: 499cc4b3aa8e0ca652336477648a0afe2b14d54f8ec297c6aad5f895050f19b1a10af97af64033ef43ac6e74864103fad3cf23a05f24b7abc735a4c2ec4a479b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
